server:
  port: 8000

spring:
  application:
    # 默认使用${spring.application.name}作为注册服务的名称
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        # nacos-server地址
        server-addr: localhost:8848
